---

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: ansible
        tasks_from: ansible.yml
        tasks:
    - include_role:
        name: add_devops_user
        tasks_from: dockerfile.yaml
